volumes:
  postgres-data:
  redis-data:

services:
  db:
    container_name: db
    image: postgis/postgis
    platform: linux/amd64
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - app_network
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network
    environment:
      RABBITMQ_DEFAULT_USER: quest
      RABBITMQ_DEFAULT_PASS: quest

networks:
  app_network:
    driver: bridge
