volumes:
  postgres-data:
  redis-data:

services:
  db:
    container_name: db
    image: postgis/postgis
    platform: linux/amd64
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis/redis-stack
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - app_network
    ports:
      - "6379:6379"
      - "8001:8001"


networks:
  app_network:
    driver: bridge