server:
  port: 19091

spring:
  application:
    name: gateway-service
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes: # 라우팅 설정
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/api/v1/hub/**
        - id: hub-route-service
          uri: lb://hub-route-service
          predicates:
            - Path=/api/v1/routes/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/v1/companies/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: slack-service
          uri: lb://slack-service
          predicates:
            - Path=/api/v1/slacks/**
        - id: delivery-agent-service
          uri: lb://delivery-agent-service
          predicates:
            - Path=/api/v1/delivery-agents/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/deliveries/**
      discovery:
        locator:
          enabled: true # 동적 라우팅 생성

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: 3600000  # 1시간
    refresh-expiration: 604800000  # 7일

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    urls[0]:
      name: Delivery API
      url: http://localhost:19100/api/delivery/v3/api-docs
    urls[1]:
      name: Delivery Agent API
      url: http://localhost:19102/api/delivery-agent/v3/api-docs
    urls[2]:
      name: Company API
      url: http://localhost:19098/api/company/v3/api-docs
    urls[3]:
      name: Order API
      url: http://localhost:19099/api/order/v3/api-docs
    use-root-path: true