server:
  port: 19093

spring:
  application:
    name: user-service
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: 3600000  # 1시간
    refresh-expiration: 604800000  # 7일

management:
  management:
    zipkin:
      tracing:
        endpoint: "http://localhost:9411/api/v2/spans"
    tracing:
      sampling:
        probability: 1.0