server:
  port: 19101

spring:
  application:
    name: delivery-route-service
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local

  # 데이터소스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA 관련 설정
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000ms

message:
  exchange: logistics                   # 기본 익스체인지
  queue:
    delivery-service: logistics.delivery-service   # 배송 요청 큐
    delivery-route: logistics.delivery-route            # 배차 요청 큐
    delivery-route-failed: logistics.route-failed      # 실패 이벤트 큐 (delivery-service로 전달)
  err:
    exchange: logistics.err
    queue:
      route: logistics.err.route
  complete:
    exchange: logistics.complete
    queue:
      order: logistics.complete.order


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

    register-with-eureka: true
    fetch-registry: true


management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0